  - type: openapi                      # OpenAPI definition import
    parameters:
      apifile:                         # String: Local file containing the OpenAPI definition, default: null, no definition will be imported
      apiurl:                          # String: URL containing the OpenAPI definition, default: null, no definition will be imported
      targeturl:                       # String: URL which overrides the target defined in the definition, default: null, the target will not be overriden
